export const technologies = [
    {value: "HTML", id: "htmlOption"},
    {value: "CSS", id: "cssOption"},
    {value: "JavaScript", id: "javaScriptOption"},
    {value: "Python", id: "pythonOption"},
    {value: "PHP", id: "phpOption"},
    {value: "React", id: "reactOption"},
    {value: "Vue", id: "vueOption"},
    {value: "Angular", id: "angularOption"},
    {value: "Svelte", id: "sveleteOption"},
    {value: "Node.js", id: "nodeOption"},
    {value: "Django", id: "djangoOption"},
    {value: "Flask", id: "flaskOption"},
    {value: "Ruby on Rails", id: "rubyOption"},
    {value: "Laravel", id: "laravelOption"},
    {value: "Spring Boot", id: "springBootOption"},
    {value: "MongoDB", id: "mongoOption"},
    {value: "MySQL", id: "mysqlOption"},
    {value: "PostgreSQL", id: "pgrsqlOption"},
    {value: "SQLite", id: "sqlOption"},
    {value: "Git", id: "gitOption"},
    {value: "Webpack", id: "webpackOption"},
    {value: "Babel", id: "babelOption"},
    {value: "Tailwind", id: "tailwindOption"},
    {value: "Bootstrap", id: "bootstrapOption"},
    {value: "Jest", id: "jestOption"},
    {value: "Mocha", id: "mochaOption"},
    {value: "Jasmine", id: "jasmineOption"},
    {value: "Cypress", id: "cypressOption"},
    {value: "AWS", id: "awsOption"},
    {value: "Azure", id: "azureOption"},
    {value: "Google Cloud", id: "googleCloudOption"},
]